accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from accounts.views import Login, Cadastro, UpdateUsuario, ProfilePage
from accounts import views as acc_views
app_name = 'accounts'

urlpatterns = [
     path('login/', Login.as_view(), name='login'),
     path('logout/', auth_views.LogoutView.as_view(), name="logout"),
     path('cadastro/', Cadastro.as_view(), name="cadastro"),
     path('editUser/<int:pk>', UpdateUsuario.as_view(), name="editar"),
     path('perfil/<int:pk>', ProfilePage.as_view(), name="perfil"),
     path("gerar_relatorio", acc_views.gerar_relatorio, name="gerar_relatorio"),
     path('reset_password/', auth_views.PasswordResetView.as_view(
          template_name="accounts/password_reset.html",
          success_url=reverse_lazy('accounts:password_reset_done')
          ), 
          name="reset_password"),
     path('password_reset_sent',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),
     path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),
     path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_complete")
]

api/urls.py
from django.urls import path, include
from api import views as api_views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt import views as jwt_views

app_name = "api"


urlpatterns = [
    path("<str:UF>/cidades/<str:city_name>", api_views.get_cidades_by_estado, name="cidadeByEstado"),
    path("imoveis/<str:UF>/<str:city_name>", api_views.get_imoveis, name="getImoveis"),
    path("meusImoveis", api_views.meusImoveis, name="meusImoveis"),
    path("imovel/<int:id>", api_views.getImovel, name="imvoelById")
]

urlpatterns += [
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

schema_view = get_schema_view(
   openapi.Info(
      title="API ALUGAAQUI",
      default_version='v1',
      description="Documentação Aluga Aqui",
    #   terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="alugaaqui@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

imovel/urls.py
from django.urls import path
from core import views as core_views
from imovel.views import CriarImovel, ListImovelUser, UpdateImovelUser, DeleteImovel
from imovel import views as imovel_views
from django.urls import include

app_name = 'imovel'

urlpatterns = [
    path('cadastrar_imovel/', CriarImovel.as_view(), name="cadastrarImovel"),
    path("detalhes/<int:id_imovel>", imovel_views.detalhes_page, name="imovel_detalhes"),
    path("enviarEmailProp/<int:id_imovel>", imovel_views.enviar_email_prop, name="enviar_email_prop"),
    path("listar_imoveis_user/", ListImovelUser.as_view(), name="imoveis_user"),
    path("editar_imovel/<int:pk>/", UpdateImovelUser.as_view(), name="editar_imovel"),
    path("delete_imovel/<int:pk>/", DeleteImovel.as_view(), name="deletar_imovel"),
]

integrador_6_periodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('imovel/', include("imovel.urls")),
    path("api/", include("api.urls"))
]

imovel/models.py
from django.db import models
from accounts.models import Usuario
from core.utils import removeAccentsOfString
# Create your models here.
from django.core.files.storage import default_storage
from integrador_6_periodo.settings import IMOVEIS_IMAGENS_DIR
import os

class Cidade(models.Model):

    nome = models.CharField(max_length=255)
    nome_sem_acentos = models.CharField(max_length=255)
    estado_sigla = models.CharField(max_length=2)
    estado = models.CharField(max_length=255)
    estado_sem_acentos = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):

        try:
            cidade = Cidade.objects.get(nome=self.nome, estado_sigla=self.estado_sigla)
        except:
            #salva somente se não houver uma cidade com aquele nome e estado
            self.nome_sem_acentos = removeAccentsOfString(self.nome)
            self.estado_sem_acentos = removeAccentsOfString(self.estado)
            super(Cidade, self).save(*args, **kwargs)


class Imovel(models.Model):

    TIPO_CHOICES = (
        ("Casa", "Casa"),
        ("Apartamento", "Apartamento"),
        ("Sobrado", "Sobrado"),
        ("Kitnet", "Kitnet"),
        ("Edícula", "Edícula"),
        ("Flat", "Flat"),
    )
    STATUS_CHOICES = (
        ("Disponível", "Disponível"),
        ("Alugado", "Alugado"),
    )

    descricao = models.CharField(max_length=500, verbose_name="Descrição do seu imovel")
    tipo = models.CharField(max_length=100, choices=TIPO_CHOICES, default="Casa")
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default="Disponível")
    valor_mensal = models.IntegerField()
    proprietario = models.ForeignKey(Usuario, default=2, blank=False, null=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Imovel"
        verbose_name_plural = "Imoveis"

    def __str__(self):
        return  str(self.id) + " - " + self.tipo

    def delete(self):

        imagens = self.imagens.all()

        for img in imagens:
            img.delete()
        
        super(Imovel, self).delete()


class ImovelImagem(models.Model):

    uri_arquivo = models.ImageField(upload_to=IMOVEIS_IMAGENS_DIR)
    imovel = models.ForeignKey(Imovel, on_delete=models.CASCADE, related_name="imagens")

    class Meta:
        verbose_name = "Imovel imagem"
        verbose_name_plural = "Imovel imagens"

    def save(self):
        if not ImovelImagem.objects.filter(imovel=self.imovel).count() >= 5:
            # cadastra somente até 5 imagens
            super(ImovelImagem, self).save()

    def delete(self):
        os.remove(self.uri_arquivo.path) #remove arquivo da pasta
        super(ImovelImagem, self).delete()


class Endereco(models.Model):
    
    logradouro = models.CharField(max_length=255)
    bairro = models.CharField(max_length=255)
    numero = models.IntegerField(null=True, blank=True, verbose_name="Número")
    ponto_de_referencia = models.CharField(max_length=255, null=True, blank=True)
    imovel = models.OneToOneField(Imovel, on_delete=models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.bairro

imovel/forms.py
from django.forms import ModelForm, forms
from django.forms.models import inlineformset_factory
from imovel.models import Imovel, ImovelImagem, Endereco


class ImovelForm(ModelForm):
    class Meta:
        model = Imovel
        fields = [
            'descricao',
            'tipo',
            'status',
            'valor_mensal'
        ]


class ImagemImovelForm(ModelForm):
    class Meta:
        model = ImovelImagem
        exclude = ['imovel']


class EnderecoImovelForm(ModelForm):
    class Meta:
        model = Endereco
        exclude = ['imovel', 'cidade']

    # def __init__(self, *args, **kwargs):
    #     super(EnderecoImovelForm, self).__init__(*args, **kwargs)
    #     self.fields['extra_field'] = forms.TextField()


ImagemFormSet = inlineformset_factory(Imovel, ImovelImagem, form=ImagemImovelForm, can_delete=False, extra=5, max_num=5, validate_max=True)
EnderecoFormSet = inlineformset_factory(Imovel, Endereco, form=EnderecoImovelForm, can_delete=False)

imovel/views.py
from django.db import transaction
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from imovel.forms import ImovelForm, ImagemFormSet, EnderecoFormSet
from imovel.models import Imovel, ImovelImagem, Cidade,Endereco
from django.shortcuts import render, redirect, HttpResponseRedirect
from api.serializers import ImovelSerializer
from django.core.mail import send_mail
from integrador_6_periodo.settings import EMAIL_HOST_USER
from django.contrib import messages

from django.http import HttpResponse

class CriarImovel(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Imovel
    form_class = ImovelForm
    template_name = 'imovel/cadastrar_imovel.html'
    success_url = reverse_lazy('core:index')

    def get(self, request, *args, **kwargs):

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = ImagemFormSet()
        formsetE = EnderecoFormSet()

        return self.render_to_response(
            self.get_context_data(form=form, formset=formset, formsetE=formsetE))

    def post(self, request, *args, **kwargs):
        cidade = None
        self.object = None

        form_class = self.get_form_class()
        form = self.get_form(form_class)

        formset = ImagemFormSet(self.request.POST, self.request.FILES)
        formsetE = EnderecoFormSet(self.request.POST)

        cidade = request.POST.get("cidade")
        estado = request.POST.get("estado")
        cidadeE = Cidade.objects.get(nome=cidade, estado_sigla=estado)

        if form.is_valid() and formset.is_valid() and formsetE.is_valid():

            form.instance.proprietario = self.request.user
            self.object = form.save()

            endereco = formsetE.save(commit=False)
            for e in endereco:
                e.imovel = self.object
                e.cidade = cidadeE
                e.save()

            media = formset.save(commit=False)
            for img in media:
                img.imovel = self.object
                img.save()
            return self.form_valid(form, formset, formsetE)
        else:
            return self.form_invalid(form, formset, formsetE)

    def form_valid(self, form, formset, formsetE):
        messages.success(self.request,'Imóvel cadastrado com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset, formsetE):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset, formsetE=formsetE))


def detalhes_page(request, id_imovel):
    imovel = None

    try:
        imovel = Imovel.objects.get(id=id_imovel)
    except:
        pass

    if imovel is None:
        return redirect("core:index")

    if imovel.status != "Disponível":
        return redirect("core:index")

    proprietario = imovel.proprietario

    imovel = ImovelSerializer(imovel, many=False).data

    if request.GET.get("success_message"):
        messages.success(request, request.GET.get("success_message"))

    return render(request, "imovel_detalhes.html", context={
        "imovel": imovel,
        "proprietario": proprietario,

    })


def enviar_email_prop(request, id_imovel):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("/")

    if request.method == "POST":
        imovel = Imovel.objects.get(id=id_imovel)

        mens = "De: " + request.user.getFullName() + "\n"

        mens += "----------------------------------\n\n"

        mens += request.POST.get("texto-mens") + "\n\n"

        mens += "----------------------------------\n"

        send_mail(
            'Alguém se interessou por seu imóvel',
            mens,
            EMAIL_HOST_USER,
            [imovel.proprietario.email],
            fail_silently=False,
        )
        success_message = "Email enviado com sucesso!"

        link_return = "/imovel/detalhes/" + str(imovel.id) + "?success_message=" + success_message + "#div-email"

        return HttpResponseRedirect(link_return)


class ListImovelUser(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Imovel
    template_name = 'imovel/lista_imoveis_user.html'

    def get_queryset(self):
        search = self.request.GET.get('search')
        queryset = None
        if search:
            queryset = Imovel.objects.filter(proprietario=self.request.user, tipo__icontains=search)
        else:
            queryset = Imovel.objects.filter(proprietario=self.request.user)
        return queryset


class UpdateImovelUser(UpdateView):
    model = Imovel
    fields = ('descricao', 'valor_mensal','status')
    template_name = 'imovel/editar_imovel.html'
    success_url = reverse_lazy('imovel:imoveis_user')

    def get_context_data(self, **kwargs):
        data = super(UpdateImovelUser, self).get_context_data(**kwargs)
        if self.request.POST:
            # cidade = self.request.POST.get("react-select-2-input")
            # estado = self.request.POST.get("react-select-3-input")
            # cidadeE = Cidade.objects.get(nome=cidade, estado_sigla=estado)

            data['formset'] = ImagemFormSet(self.request.POST, self.request.FILES, instance=self.object)
            data['formsetE'] = EnderecoFormSet(self.request.POST, instance=self.object)
            # data['cidade'] = cidadeE


        else:
            # end = Endereco.objects.get(imovel=self.object)
            # cidadeE = Cidade.objects.get(nome=end.cidade)
            data['formset'] = ImagemFormSet(instance=self.object)
            data['formsetE'] = EnderecoFormSet(instance=self.object)
            # data['cidade'] = cidadeE

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        formsetE = context['formsetE']

        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid() and formsetE.is_valid():
                formsetE.instance = self.object
                formset.instance = self.object
                formset.save()
                formsetE.save()

        return super(UpdateImovelUser, self).form_valid(form)


class DeleteImovel(DeleteView):
    model = Imovel
    template_name = 'imovel/delete_imovel.html'
    success_url = reverse_lazy('imovel:imoveis_user')

imovel/templates/imovel/cadastrar_imovel.html
{# Load the tag library #}
{% extends 'basepage.html' %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% block head %}
<title>Cadastro de Imóvel</title>
<link href="{% static 'css/all.css' %}" rel="stylesheet">
{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block page %}

<div class="container">
    <fieldset class="p-2">
        <legend class='text-center'>Cadastre seu Imovel <i class="fas fa-home"></i></legend>
        <form enctype="multipart/form-data" method="post" action="">
            {% csrf_token %}
            <fieldset class="border p-4 m-2">
                <legend class="lead"> Sobre o Imóvel</legend>
                {% bootstrap_form form %}
            </fieldset>
            <fieldset class="border p-4 m-2">
                {{ formsetE.management_form }}

                <legend class="lead"> Endereço do Imóvel <i class="fas fa-map-marker-alt"></i></legend>
                <div id="endereco" class="form-inline form-group">
                    <div id="item-00" class="mb-2">
                        <div id="form-busca">

                        </div>
                    </div>
                    {% for item_form in formsetE %}

                    <div id="item-{{ forloop.counter0 }}" class="p-2">

                        {#                                {% bootstrap_form item_form %}#}
                        {% bootstrap_form item_form layout="horizontal" size="small" label_class="form-label col-md-3" %}
                        <br />
                    </div>
                    {% endfor %}


                </div>
            </fieldset>
            <fieldset class="border p-4 m-2">
                {{ formset.management_form }}

                <legend class="lead"> Imagens <i class="fas fa-images"></i></legend>

                <div id="img" class="form-group">
                    {% for item_order_form in formset %}

                    <div id="item-{{ forloop.counter0 }}" class="m-4 img-field" hidden="true">

                        {% bootstrap_form item_order_form show_label=False %}
                        <hr>
                    </div>
                    {% endfor %}
                </div>
                <a class="btn btn-success mt-2" id="add-item"><i class="fa fa-plus"></i> Adicionar foto</a>
            </fieldset>
            <div class="buttons m-2">
                <a href="#" class="btn btn-danger pull-right "><i class="fa fa-times"></i> Cancelar</a>
                <button class="btn btn-primary pull-right " value="Save" style="margin-right: 20px"><i
                        class="fa fa-floppy-o"></i> Cadastrar
                </button>
            </div>
        </form>
    </fieldset>
</div>
<script type="text/babel" src="{% static 'js/cadastro_imovel_react.js' %}"></script>
{#    <script type="text/html" id="item-order">#}
{#        <div id="item-__prefix__" style="margin: 24px">#}
{#            {{ formset.empty_form|crispy }}#}
{#            {% bootstrap_form formset.empty_form show_label=False %}#}
{#            <hr>#}
{#        </div>#}
{#    </script>#}
{% endblock %}

imovel/templates/imovel/delete_imovel.html
{% extends 'basepage.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block page %}


<div class="row">
    <div class="col-md-6 mx-auto">
        <h3>Excluir registros</h3>
        <p class="lead">Confirme para excluir</p>

        <hr>
        <form method="post" action="">
            <p>Deseja excluir o registro: {{ object }} ?</p>

            {% csrf_token %}
            {{ form|crispy }}

            <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Excluir</button>
            <a href="{% url 'imovel:imoveis_user' %}" class="btn btn-warning" style="color:#fcfaff;" ><i class="fas fa-times"></i> Cancelar</a>

        </form>
    </div>

</div>

{% endblock %}

imovel/templates/imovel/editar_imovel.html
{# Load the tag library #}
{% extends 'basepage.html' %}
{% load static %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% block head %}
<title>Cadastro de Imóvel</title>
<link href="{% static 'css/all.css' %}" rel="stylesheet">
{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block page %}

<div class="container">
    <fieldset class="p-2">
        <legend class='text-center'>Atualize os dados do seu Imovel <i class="fas fa-home"></i></legend>
        <form enctype="multipart/form-data" method="post" action="">
            {% csrf_token %}
            <fieldset class="border p-4 m-2">
                <legend class="lead"> Sobre o Imóvel</legend>
                {% bootstrap_form form %}
            </fieldset>
            <fieldset class="border p-4 m-2">
                {{ formsetE.management_form }}

                <legend class="lead"> Endereço do Imóvel <i class="fas fa-map-marker-alt"></i></legend>
{#                <div id="endereco" class="form-inline form-group">#}
{#                    <input id="cid" name="cid" value="{{ cidade.nome }}" hidden>#}
{#                    <input id="est" name="est" value="{{ cidade.estado_sigla }}" hidden>#}
{#                </div>#}
{#                <div>#}
{#                    <span id="form-cidade"></span>#}
{#                    <span id="form-estado"></span>#}
{#                </div>#}
                {% for item_form in formsetE %}

                    <div id="item-{{ forloop.counter0 }}" class="p-2">

                        {#                                {% bootstrap_form item_form %}#}
                        {% bootstrap_form item_form layout="horizontal" size="small" label_class="form-label col-md-3" %}
                        <br/>
                    </div>
                {% endfor %}


            </fieldset>
            <fieldset class="border p-4 m-2">
                {{ formset.management_form }}

                <legend class="lead"> Imagens <i class="fas fa-images"></i></legend>

                <div id="img" class="form-group">
                    {% for item_order_form in formset %}

                        <div id="item-{{ forloop.counter0 }}" class="m-4 img-field" hidden="true">

                            {% bootstrap_form item_order_form show_label=False %}
                            <hr>
                        </div>
                    {% endfor %}
                </div>
                <a class="btn btn-success mt-2" id="add-item"><i class="fa fa-plus"></i> Adicionar foto</a>
            </fieldset>
            <div class="buttons m-3 p-2">
                <a href="{% url 'imovel:imoveis_user' %}" class="btn btn-danger pull-right "><i class="fa fa-times"></i>
                    Cancelar</a>
                <button type="submit" class="btn btn-primary pull-right " value="Save" style="margin-right: 20px"><i
                        class="fas fa-redo-alt"></i> Atualizar
                </button>
            </div>
        </form>
    </fieldset>
</div>
<script type="text/babel" src="{% static 'js/edit_react.js' %}"></script>

{% endblock %}

imovel/templates/imovel/lista_imoveis_user.html
{% extends 'basepage.html' %}
{% include 'imovel/delete_imovel.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block head %}
<!-- Custom CSS -->
<title>Seus Imóveis</title>
<link rel="stylesheet" href="{% static 'css/imoveis_list_user.css' %}">

{% endblock %}
{% block page %}
<div class="container">
    <div class="row justify-content-md-center mb-5">
        <div class="col-md-4 col-sm-12 d-flex flex-column justify-content-center align-items-center">
            <h3 class="align-self-start">Seus Imoveis <i class="fas fa-home"></i></h3>
        </div>
        <div class="col-md-4 col-sm-8 search-div">
            <form method="GET" id="search-form">
                <div class="row">
                    <div class="input-group col-md-4">
                        <input class="form-control" type="search" id="search" name="search"
                            placeholder="Digite o tipo de imóvel para buscar..." value="{{ request.GET.search }}">
                        <span class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="search-btn">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-11"></div>
        <div class="col-sm-1" style="text-align: center; font-size: 12px; font-weight: bold">
            Gerar Relatório<br>
            <a target="_blank" href="{% url 'accounts:gerar_relatorio' %}">
                <img src="/static/imagens/outline_assignment_black_24dp.png" style="width: 35px;" alt="Gerar Relatório"
                    srcset="">
            </a></div>

    </div>
    {% for imovel in imovel_list %}
    {#--------------------------#}
    <div class="row justify-content-md-center">
        <div class="col-md-8">

            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{% static imovel.imagens.all.0.uri_arquivo %}" alt="..." class="img-fluid"
                            style="height: 205px;width: 300px" />
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ imovel.tipo }}</h5>
                            <p class="card-text">
                                {{ imovel.endereco.cidade }},
                                {{ imovel.endereco.bairro }}
                                <span>N° {{ imovel.endereco.numero }}</span><br>
                                {% if imovel.status == 'Disponível' or imovel.status == 'Disponivel'%}
                                <span class="badge alert-success">Disponível</span>
                                {% elif imovel.status == 'Alugado' %}
                                <span class="badge alert-warning">Alugado</span>
                                {% endif %}

                            </p>

                            <p class="">

                                <a href="{% url 'imovel:editar_imovel' imovel.id %}" class="btn btn-primary btn_edit"><i
                                        class="far fa-edit"></i> Editar</a>

                                <a href="{% url 'imovel:deletar_imovel' imovel.id %}" class="btn btn-danger"><i
                                        class="far fa-trash-alt"></i> Excluir</a>

                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

<script>
    $(document).ready(function () {

        var searchBtn = $('#search-btn');
        var searchForm = $('#search-form');

        $(searchBtn).on('click', function () {
            searchForm.submit();
        });

    });
</script>
{% endblock %}