accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from accounts.views import Login, Cadastro, UpdateUsuario, ProfilePage
from accounts import views as acc_views
app_name = 'accounts'

urlpatterns = [
     path('login/', Login.as_view(), name='login'),
     path('logout/', auth_views.LogoutView.as_view(), name="logout"),
     path('cadastro/', Cadastro.as_view(), name="cadastro"),
     path('editUser/<int:pk>', UpdateUsuario.as_view(), name="editar"),
     path('perfil/<int:pk>', ProfilePage.as_view(), name="perfil"),
     path("gerar_relatorio", acc_views.gerar_relatorio, name="gerar_relatorio"),
     path('reset_password/', auth_views.PasswordResetView.as_view(
          template_name="accounts/password_reset.html",
          success_url=reverse_lazy('accounts:password_reset_done')
          ), 
          name="reset_password"),
     path('password_reset_sent',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),
     path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),
     path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_complete")
]

api/urls.py
from django.urls import path, include
from api import views as api_views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt import views as jwt_views

app_name = "api"


urlpatterns = [
    path("<str:UF>/cidades/<str:city_name>", api_views.get_cidades_by_estado, name="cidadeByEstado"),
    path("imoveis/<str:UF>/<str:city_name>", api_views.get_imoveis, name="getImoveis"),
    path("meusImoveis", api_views.meusImoveis, name="meusImoveis"),
    path("imovel/<int:id>", api_views.getImovel, name="imvoelById")
]

urlpatterns += [
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

schema_view = get_schema_view(
   openapi.Info(
      title="API ALUGAAQUI",
      default_version='v1',
      description="Documentação Aluga Aqui",
    #   terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="alugaaqui@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

core/urls.py
from django.urls import path
from core.views import index_page
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", index_page.as_view(), name="index"),

    path("imoveis", core_views.imoveis_page, name="imoveis_page"),
]

integrador_6_periodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('imovel/', include("imovel.urls")),
    path("api/", include("api.urls"))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
# Create your models here.


class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email é obrigatorio')
        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser=True')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff=True')
        return self._create_user(email, password, **extra_fields)


class Usuario(AbstractUser):

    email = models.EmailField("email", unique=True)
    nome = models.CharField(max_length=45)
    sobrenome = models.CharField(max_length=45)
    telefone = models.CharField(max_length=45)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # removes email from REQUIRED_FIELDS

    def __str__(self):
        return self.nome + " " + self.sobrenome + "\n email " + self.email
    
    def getFullName(self):
        return self.nome + " " + self.sobrenome
    
    objects = UsuarioManager()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.forms import ModelForm
from .models import Usuario


class CreateUserForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'nome', 'telefone', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["username"]

        if commit:
            user.save()

        return user


class ChangeUserForm(UserChangeForm):
    class Meta:
        model: Usuario

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data["email"]
        user.nome = self.cleaned_data["nome"]
        user.sobrenome = self.cleaned_data["sobrenome"]
        user.telefone = self.cleaned_data["telefone"]

        if commit:
            user.save()

        return user


class UpdatePerfil(ModelForm):
    class Meta:
        model = Usuario
        fields = ('username', 'nome', 'telefone')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Usuario.objects.get(email=email)
        except Usuario.DoesNotExist:
            return email
        raise forms.ValidationError(f'Email {email} já exite')

    def save(self, commit=True):
        account = super(UpdatePerfil, self).save(commit=False)
        account.username = self.cleaned_data['username']
        # account.email = self.cleaned_data['email']
        account.nome = self.cleaned_data['nome']
        account.telefone = self.cleaned_data['telefone']
        if commit:
            account.save()
        return account

accounts/views.py
from django.contrib.auth.views import LoginView
from accounts.models import Usuario
from imovel.models import Imovel
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView
from accounts.forms import CreateUserForm, ChangeUserForm, UpdatePerfil
from django.contrib.auth.mixins import LoginRequiredMixin
# ------- REDIRECT/RESPONSE -------#
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, redirect, HttpResponseRedirect
# ------- REDIRECT/RESPONSE -------#
# ------- RELATÓRIO -------#
from io import BytesIO
from xhtml2pdf import pisa
from django.template.loader import get_template
# ------- RELATÓRIO -------#


class Login(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('core:index')


class Cadastro(CreateView):
    form_class = CreateUserForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/cadastro.html'


class UpdateUsuario(UpdateView, LoginRequiredMixin):
    login_url = reverse_lazy('login')
    model = Usuario
    # fields = ('username', 'nome', 'telefone')
    template_name = 'accounts/update_usuario.html'
    form_class = UpdatePerfil
    success_message = 'Dados alterados com sucesso!'


    def get_success_url(self):
        return reverse('accounts:perfil',kwargs={"pk": self.request.user.id})

class ProfilePage(TemplateView):
    template_name = 'accounts/profile.html'
    def get_context_data(self, **kwargs):
        context = super(ProfilePage, self).get_context_data(**kwargs)
        # pass user id for which profile page was requested
        context['requested_profile_id'] = self.kwargs.get('pk')

        return context
def gerar_relatorio(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(request, "/")

    usuario = request.user

    imoveis = Imovel.objects.filter(proprietario = usuario)

    qtd_imoveis = imoveis.count()
    qtd_imoveis_diponíveis = 0
    qtd_imoveis_alugados = 0
    val_recebido_por_mes = 0
    val_n_recebido_por_mes = 0
    total_val_im = 0

    for imovel in imoveis:
        if imovel.status == "Disponível":
            qtd_imoveis_diponíveis += 1
            val_n_recebido_por_mes += imovel.valor_mensal
        elif imovel.status == "Alugado":
            qtd_imoveis_alugados += 1
            val_recebido_por_mes += imovel.valor_mensal

    template = get_template("relatorio.html")
    html  = template.render({
        "usuario" : request.user,
        "qtd_im_disp" : qtd_imoveis_diponíveis,
        "qtd_im_alug" : qtd_imoveis_alugados,
        "val_receb_mes" : val_recebido_por_mes,
        "val_n_receb_mes" : val_n_recebido_por_mes,
        })
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)

    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')


    return HttpResponseRedirect(request, "/")

accounts/templates/accounts/cadastro.html
{% load static %}
{% load bootstrap4 %}
{% block head %}
<title>Cadastro</title>
<link href="{% static 'css/all.css' %}" rel="stylesheet">
<link rel="stylesheet" href="/static/css/cadastro.css">
{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block page %}

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto card-div">
            <div class="card card-signin my-5 shadow rounded-3">

                <div class="card-body ">
                    <div class="row justify-content-center px-3 mt-3 mb-1"><img id="logo-cadastro"
                            src="{% static 'imagens/Alugaqui - Logo-01.png' %}">
                    </div>
                    <h5 class="card-title text-center font-weight-light mb-3">Faça seu Cadastro</h5>
                    <form method="post">
                        {% csrf_token %}

                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ field.name|title }} {{ error|escape }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ error|escape }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Email" name="username" id="id_username"
                                required="">
                            <p class="errorlist">{{ form.errors.email }}</p>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Nome" name="nome" maxlength="45"
                                required="" id="id_nome">
                            <p class="errorlist">{{ form.errors.nome }}</p>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-signature"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Telefone" name="telefone" required=""
                                id="id_telefone">
                            <p class="errorlist">{{ form.errors.telefone }}</p>
                            <div class="input-group-append">
                                <div class="input-group-text">

                                    <span class="fas fa-phone-alt"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" class="form-control" placeholder="Senha" autocomplete="new-password"
                                name="password1" required="" id="id_password1">

                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>

                        </div>
                        <div class="input-group mb-3">
                            <input type="password" class="form-control" placeholder="Confirme sua senha"
                                name="password2" autocomplete="new-password" required="" id="id_password2">

                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-8">

                            </div>
                            <!-- /.col -->
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">Cadastre-se</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>

                    <p class="mb-0">
                        <span>Já tem uma conta? <a href="{% url 'accounts:login' %}"
                                class="text-center">Entrar</a></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {% bootstrap_field form.username %}#}
{#        <button type="submit" class="btn btn-primary">#}
{#            Submit#}
{#        </button>#}
{#    </form>#}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
<script type="text/javascript">
    $("#id_telefone").mask("(00) 0000-0000");
</script>
{% endblock %}

accounts/templates/accounts/login.html
{# Load the tag library #}
{% load static %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block head %}
<title>Entrar</title>
<link href="{% static 'css/all.css' %}" rel="stylesheet">
<link rel="stylesheet" href="/static/css/login.css">
{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% block page %}

<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto card-div" id="div-card-login">
            <div class="card card-signin my-5 shadow rounded-3">
                <div class="row justify-content-center px-3 mt-3 mb-1">
                    <img id="logo-login" src="{% static 'imagens/Alugaqui - Logo-01.png' %}">
                </div>
                <div class="card-body ">
                    <h5 class="card-title text-center font-weight-light">Acesse sua conta</h5>
                    <form method="post">
                        {% csrf_token %}

                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ field.name|title }} {{ error|escape }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>{{ error|escape }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                        {% endif %}

                        <div class="input-group mb-3">
                            <input type="email" class="form-control" placeholder="Email" name="username">
                            <p class="errorlist">{{ form.errors.username }}</p>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password">
                            <p class="errorlist">{{ form.errors.password }}</p>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">
                                <p class="mb-1">
                                    <a href="/accounts/reset_password/">Esqueci a minha senha!</a>
                                </p>
                                <p class="mb-0">
                                    <span>Não tem uma conta?<a href="{% url 'accounts:cadastro' %}" class="text-center">
                                            Registre-se</a></span>
                                </p>
                            </div>
                            <!-- /.col -->
                            <div class="col-4">
                                <button type="submit" id="btn-entrar" class="btn btn-primary btn-block">Entrar</button>
                            </div>
                            <!-- /.col -->
                        </div>
                </div>
                <div class="card-body" style="padding-top: 0px;">
                    <hr>
                    <div class="col-12" style="display: flex; justify-content: center; margin-top: 10px">
                        <div class="google-btn btn-primary">
                            <div class="google-icon-wrapper">
                                <img class="google-icon"
                                    src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg" />
                            </div>
                            <p class="btn-text"><b><a style="color: white;"
                                        href="{% provider_login_url 'google' %}">Entrar com Google</a></b></p>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'basepage.html' %}

{% load static %}
{% load bootstrap4 %}

{% block head %}
    <title>Recuperar senha</title>
{% endblock %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block page %}
    <p>Insira de email para receber as intruções</p>
    <form method="post">
        {% csrf_token %}
        <div class="col-md-6">
            {% bootstrap_form form %}
        </div>

        <button type="submit" class="btn btn-primary mt-3">Enviar</button>
    </form>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'basepage.html' %}
{% block page %}
    <h3>Redefinição de senha concluída</h3>
    <a href="{% url "login" %}">Login</a>
{% endblock %}

accounts/templates/accounts/password_reset_form.html
<h3>Insira a nova senha</h3>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Atualizar senha</button>
</form>

accounts/templates/accounts/password_reset_sent.html
{% extends 'basepage.html' %}
{% block page %}
    <h3>Verifique seu E-mail</h3>
    <p>Foi enviado um link para o e-mail informado, verifique a caixa de entrada e spam do seu e-mail.</p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'basepage.html' %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
<title>Perfil</title>
<link href="{% static 'css/all.css' %}" rel="stylesheet">
<link rel="stylesheet" href="/static/css/cadastro.css">
{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


{% block page %}

    <div class="container">
        {% if user.is_authenticated and user.id == requested_profile_id %}

            <div class="container p-5">
                <div class="row">

                    <div class="col-md-6 img">
                        <img src="{% static 'imagens/2189.jpg' %}"
                             alt="" class="img-rounded"  style="width: 200px">
                    </div>
                    <div class="col-md-6 details" style="border-left:3px solid #ded4da;">
                        <div class="pull-right">
                            <a class="btn btn-outline-secondary btn-sm" href="{% url "accounts:editar" user.id %}">Editar
                                <i class="fas fa-cog" ></i>
                            </a>

                        </div>
                        <blockquote>
                            <h5>{{ user.nome }}</h5>
                            <small><cite title="Source Title">Chicago, United States of America <i
                                    class="icon-map-marker"></i></cite></small>
                        </blockquote>
                        <p style="font-size:15px;font-weight:bold;">
                            {{ user.email }} <br>
                            {{ user.telefone }} <br>
                            June 18, 1990
                        </p>
                    </div>
                </div>
            </div>

        {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/update_usuario.html
{% extends 'basepage.html' %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
<title>Cadastro</title>
<link href="{% static 'css/all.css' %}" rel="stylesheet">
<link rel="stylesheet" href="/static/css/cadastro.css">
{% endblock %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block page %}

    <div class="container">
        <div class="row">
{#            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto ">#}
                <div class="container my-5 shadow rounded-3">

                    {#                    <div class="row justify-content-center px-3 mt-3 mb-1"><img id="logo-cadastro"#}
                    {#                            src="{% static 'imagens/Alugaqui - Logo-01.png' %}">#}
                    {#                    </div>#}

                    <form method="post">
                        {% csrf_token %}

                        {% bootstrap_form form %}
                        <div class="row">
                            <div class="col-8">

                            </div>
                            <!-- /.col -->
                            <div class="col-4 m-5">
                                <button type="submit" class="btn btn-primary btn-block">Atualizar</button>
                                <a type="button" class="btn btn-warning btn-block" href="{% url 'core:index' %}">Cancelar</a>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>

                </div>
{#            </div>#}
        </div>
    </div>

{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {% bootstrap_field form.username %}#}
{#        <button type="submit" class="btn btn-primary">#}
{#            Submit#}
{#        </button>#}
{#    </form>#}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
<script type="text/javascript">
    $("#id_telefone").mask("(00) 0000-0000");
</script>
{% endblock %}