accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from accounts.views import Login, Cadastro, UpdateUsuario, ProfilePage
from accounts import views as acc_views
app_name = 'accounts'

urlpatterns = [
     path('login/', Login.as_view(), name='login'),
     path('logout/', auth_views.LogoutView.as_view(), name="logout"),
     path('cadastro/', Cadastro.as_view(), name="cadastro"),
     path('editUser/<int:pk>', UpdateUsuario.as_view(), name="editar"),
     path('perfil/<int:pk>', ProfilePage.as_view(), name="perfil"),
     path("gerar_relatorio", acc_views.gerar_relatorio, name="gerar_relatorio"),
     path('reset_password/', auth_views.PasswordResetView.as_view(
          template_name="accounts/password_reset.html",
          success_url=reverse_lazy('accounts:password_reset_done')
          ), 
          name="reset_password"),
     path('password_reset_sent',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),
     path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
         name="password_reset_confirm"),
     path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_complete")
]

api/urls.py
from django.urls import path, include
from api import views as api_views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt import views as jwt_views

app_name = "api"


urlpatterns = [
    path("<str:UF>/cidades/<str:city_name>", api_views.get_cidades_by_estado, name="cidadeByEstado"),
    path("imoveis/<str:UF>/<str:city_name>", api_views.get_imoveis, name="getImoveis"),
    path("meusImoveis", api_views.meusImoveis, name="meusImoveis"),
    path("imovel/<int:id>", api_views.getImovel, name="imvoelById")
]

urlpatterns += [
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

schema_view = get_schema_view(
   openapi.Info(
      title="API ALUGAAQUI",
      default_version='v1',
      description="Documentação Aluga Aqui",
    #   terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="alugaaqui@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

core/urls.py
from django.urls import path
from core.views import index_page
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", index_page.as_view(), name="index"),

    path("imoveis", core_views.imoveis_page, name="imoveis_page"),
]

imovel/urls.py
from django.urls import path
from core import views as core_views
from imovel.views import CriarImovel, ListImovelUser, UpdateImovelUser, DeleteImovel
from imovel import views as imovel_views
from django.urls import include

app_name = 'imovel'

urlpatterns = [
    path('cadastrar_imovel/', CriarImovel.as_view(), name="cadastrarImovel"),
    path("detalhes/<int:id_imovel>", imovel_views.detalhes_page, name="imovel_detalhes"),
    path("enviarEmailProp/<int:id_imovel>", imovel_views.enviar_email_prop, name="enviar_email_prop"),
    path("listar_imoveis_user/", ListImovelUser.as_view(), name="imoveis_user"),
    path("editar_imovel/<int:pk>/", UpdateImovelUser.as_view(), name="editar_imovel"),
    path("delete_imovel/<int:pk>/", DeleteImovel.as_view(), name="deletar_imovel"),
]

integrador_6_periodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('imovel/', include("imovel.urls")),
    path("api/", include("api.urls"))
]

core/views.py
from django.views.generic import TemplateView

from django.shortcuts import render, redirect
from imovel.models import Cidade

class index_page(TemplateView):
    template_name = 'index.html'

def imoveis_page(request):

    if request.method == "GET":
        cidade = None

        try:
            cidade = Cidade.objects.get(nome=request.GET["cidade"], estado_sigla=request.GET["estado"])
        except:
            return redirect(request, "core:index")
            pass

        return render(request, "listagem_imoveis.html", context = {"cidade" : cidade})

core/templates/basepage.html
{% load static %}

<!DOCTYPE html>
<html lang="pt" style="height: 100%">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/all.css' %}" rel="stylesheet">
    <!--load all styles icon-->

    <!-- Css Bootstrap -->
    <link rel="stylesheet" href="{% static 'bootstrap-5.0.0/bootstrap-5.0.0-beta2-dist/css/bootstrap.min.css' %}">
    <!-- Css Bootstrap -->
    <link rel="stylesheet" href="{% static 'bootstrap-5.0.0/bootstrap-5.0.0-beta2-dist/css/bootstrap.min.css' %}">

    <!-- popper -->
    <script src="{% static 'bootstrap-5.0.0/bootstrap-5.0.0-beta2-dist/js/popper.min.js' %}"></script>

    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap-5.0.0/bootstrap-5.0.0-beta2-dist/js/bootstrap.min.js' %}"></script>

    <!-- Custom CSS -->
    <script src="{% static 'React/react.development.js' %}"></script>
    <script src="{% static 'React/react-dom.development.js' %}"></script>

    <!-- React -->
    <!-- Auto Complete -->
    <script src="{% static 'React/prop-types-15.7.2.js' %}"></script>
    <!-- <script src="https://unpkg.com/classnames@2.2.6/index.js"></script>  -->
    <script src="{% static 'React/react-input-autosize-2.2.2.js' %}"></script>
    <script src="{% static 'React/emotion-10.0.27.umd.min.js' %}"></script>
    <script src="{% static 'React/react-select-2.4.4.js' %}"></script>
    <!-- Auto Complete -->

    <!-- React -->

    <!-- Babel -->
    <script src="{% static 'React/babel.min.js' %}"></script>

    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/basepage.css' %}">

    {% block head %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img id="img-logo" src="{% static 'imagens/Alugaqui - Logo-02.png' %}" alt=""
                 class="d-inline-block align-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- <div class="d-flex collapse navbar-collapse"> -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav nav-pills ml-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Procurar Imóveis</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url "imovel:cadastrarImovel" %}">Cadastrar
                            Imóveis</a>
                    </li>
                {% endif %}
            </ul>

            {% if user.is_authenticated %}
                <!-- Funcionalidades -->
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Minha Conta
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url "accounts:perfil" user.id %}"><i class="far fa-user-circle"></i> Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url "imovel:imoveis_user" %}"><i class="far fa-list-alt"></i> Meus Imóveis</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Sair
                                </a>
                            </li>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- Funcionalidades -->

            {% else %}
                <li class="nav-item" id="login-li">
                    <a id="btn-login" href="{% url 'accounts:login' %}" class="btn btn-sm nav-link">Entrar</a>
                </li>
            {% endif %}

            <!-- </div> -->
        </div>
    </div>
</nav>
<div class="container">
{% include 'messages.html' %}
</div>
<div class="container" id="sheet">
    {% block page %}


    {% endblock %}
</div>
<!-- Footer -->
<section id="footer">
    <div class="container">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Desenvolvedores</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href="#"><i class="fa fa-angle-double-right"></i>Maria Jakeline Freitas da Silva</a></li>
                    <li><a href="#">
                        <a href="https://github.com/jakeline-freitas" target="_blank"><i class="fa fa-github"></i></a>
                        <a href="https://www.linkedin.com/in/maria-jakeline-360b93124/" target="_blank"><i
                                class="fa fa-linkedin"></i></a>
                    </a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i>Natan Almeida de Lima</a></li>
                    <li><a href="#">
                        <a href="https://github.com/kanatius" target="_blank"><i class="fa fa-github"></i></a>
                        <a href="https://www.linkedin.com/in/natan-almeida-2662a0171/" target="_blank"><i
                                class="fa fa-linkedin"></i></a>
                    </a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Sobre Nós</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href="#!"><i class="fa fa-angle-double-right"></i>Quem Somos</a></li>
                    <li><a href="#!"><i class="fa fa-angle-double-right"></i>O Que Fazemos</a></li>
                    <li><a href="#!"><i class="fa fa-angle-double-right"></i>Como Fazemos</a></li>
                    <li><a href="#!"><i class="fa fa-angle-double-right"></i>Onde Fazemos</a></li>
                    <li><a href="#!"><i class="fa fa-angle-double-right"></i><i class="fa fa-youtube"></i></a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Instituto Responsável</h5>
                <img id="if-logo-footer" src="/static/imagens/ifrn_logo_preta.png" alt="">
                <!-- <ul class="list-unstyled quick-links">
                              <li><a href="#!"><i class="fa fa-angle-double-right"></i>Home</a></li>
                              <li><a href="#!"><i class="fa fa-angle-double-right"></i>About</a></li>
                              <li><a href="#!"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
                              <li><a href="#!"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
                              <li><a href="#!" title="Design and developed by"><i class="fa fa-angle-double-right"></i>Imprint</a></li>
                          </ul> -->
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                <ul class="list-unstyled list-inline social text-center">
                    <li class="list-inline-item"><a href="#!"><i class="fa fa-github"></i></a></li>
                    <li class="list-inline-item"><a href="#!"><i class="fa fa-linkedin"></i></a></li>
                    <li class="list-inline-item"><a href="#!"><i class="fa fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a href="#!"><i class="fa fa-google-plus"></i></a></li>
                    <li class="list-inline-item"><a href="#!"><i class="fa fa-envelope"></i></a></li>
                </ul>
            </div>
            <hr>
        </div>
        <!-- <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                      <p><u><a href="#!">National Transaction Corporation</a></u> is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]</p>
                      <p class="h6">© All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Sunlimetech</a></p>
                  </div>
                  <hr>
              </div>	 -->
    </div>
</section>
<!-- ./Footer -->
<script>
    setTimeout(function (){
        if ($('#msg').length > 0){
            $('#msg').remove();
        }
    },2000)
</script>
</body>

</html>

core/templates/index.html
{% extends 'basepage.html' %}

{% load static%}
{% block head %}
<title>Procurar Imóveis</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}


{% block page %}
<h4>Buscar imóveis</h4>
<br>
<form action="{% url 'core:imoveis_page' %}" id="form-busca">
</form>

<script type="text/babel" src="/static/js/index_react.js"></script>

{% endblock %}

core/templates/listagem_imoveis.html
{% extends 'basepage.html' %}
{% load static %}
{% block head %}
    <title>Imóveis</title>
    <script type="text/babel" src="{% static 'js/listagem_imoveis.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/listagem_imoveis.css' %}">
{% endblock %}


{% block page %}
<hr/>
<h4 id="titulo">Imóveis disponíveis na cidade de {{cidade.nome}}-{{cidade.estado_sigla}}</h4>
<hr id="hr-bottom"/>
<input type="text" id="cidade" value="{{cidade.nome}}" hidden>
<input type="text" id="estado" value="{{cidade.estado_sigla}}" hidden>
<div id="imoveis-list">

</div>
{% endblock %}

core/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2 " id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}